Add reconnection mechanism
overextended/oxmysql pull request #119
Opened 2022-05-30 01:29 UTC by ch-jack

Added the reconnection mechanism and the reconnection time configuration "mysql_reconnect_time", if the time is 0, no reconnection

2022-05-31 15:30 UTC, darksaid98 requested changes
This PR still needs the approval of Linden, Dunak, Luke, or Doka. Personally, I don't have a use case for this except if I forget to start the local dev DB but I guess someone might. 

Either way thanks for contributing even if it doesn't get merged 👍.

2022-05-31 15:30 UTC, darksaid98 commented on src/database/index.ts
> +  setTimeout(() => {
Not sure why this `setTimeout` is here. I know it was there before your PR, testing worked fine without it so not sure what it's meant to accomplish. 
```suggestion
```

2022-05-31 15:30 UTC, darksaid98 commented on src/database/index.ts
> +        delete pool;
Prevents building for me because of Strict mode. Should be removed since `pool` is reassigned in the next function call anyways.
```suggestion
```

2022-05-31 15:30 UTC, darksaid98 commented on src/database/index.ts
>    });
Remove if you deleted `setTimeout`.
```suggestion
```

2022-05-31 15:30 UTC, darksaid98 commented on src/database/index.ts
> +        };
```suggestion
        if (mysql_reconnect_time > 0) setTimeout(mysqlInit, mysql_reconnect_time);
```

2022-05-31 15:30 UTC, darksaid98 commented on src/database/index.ts
> +const mysqlInit = (() => {
```suggestion
const mysqlInit = () => {
```

2022-05-31 15:30 UTC, darksaid98 commented on src/database/index.ts
> +})
```suggestion
}
```

2022-05-31 17:08 UTC, darksaid98 requested changes
Tiny change =).

2022-05-31 17:08 UTC, darksaid98 commented on src/database/index.ts
> +    });
Super nitpicky formatting.
```suggestion
  pool.query(mysql_transaction_isolation_level, (err) => {
    if (err) {
      console.error(`^3Unable to establish a connection to the database!\n^3[${err}]^0`);
      if (mysql_reconnect_time > 0) setTimeout(mysqlInit, mysql_reconnect_time);
      return;
    }
    console.log(`^2Database server connection established!^0`);
    serverReady = true;
  });
```

2022-05-31 17:35 UTC, darksaid98 approved these changes
Works as intended 👍.

2022-05-31 17:35 UTC, darksaid98 approved these changes

2022-05-31 21:36 UTC, thelindat commented
Use case is pretty minimal, I assume this is supposed to resolve ECONNTIMEOUT that tends to happen from server hitches at boot?

2022-06-01 01:14 UTC, ch-jack commented
> 用例非常少，我认为这应该解决 ECONNTIMEOUT 往往会在启动时服务器故障发生？

Yes, mainly to solve this problem

2022-06-25 18:12 UTC, thelindat commented
ECONNTIMEOUT can be resolved by loading large assets before oxmysql (maps, cars, etc). I'd rather handle this type of reconnection attempt in a different way.

2022-06-25 18:12 UTC, closed without merging