WIP (Transactions)
overextended/oxmysql pull request #20
Opened 2021-09-19 03:05 UTC by darksaid98

**Todo:**
- Error handling. (Might not want to spam console because of failed transactions, kind of need some input here)
- Docs?
- ...

**Example usage:**

```Lua
local queries = { -- Shared Param Format
    'INSERT INTO `bans` (token) VALUES (:test)',
    'INSERT INTO `bans` (token) VALUES (:test)',
    'INSERT INTO `bans` (token) VALUES (:test)',
}
local params = { ['test'] = 'thisisatestvalue' }
    
exports.oxmysql:transaction(queries, params, function(result) 
    print(result)
end)
```

```Lua
local queries = { -- Specific Format
    { query = 'INSERT INTO `test` (id, text) VALUES (:nene, :meme)', values = { ['nene'] = 'thisisatest', ['meme'] = 'this is a text' } },
    { query = 'INSERT INTO `test` (id, text) VALUES (:nene, :meme)', values = { ['nene'] = 'thisisates2', ['meme'] = 'this is a text' } },
    { query = 'INSERT INTO `test` (id) VALUES (:nene)', parameters = { ['nene'] = 'thisisatest4' } },
}

exports.oxmysql:transaction(queries, function(result) 
    print(result)
end)
```

2021-09-19 15:21 UTC, darksaid98 commented
The exports now accept a boolean value indicating whether to print errors on failure to console. If set to `false` no errors will be logged. By default, it is assumed as `true`.

```Lua
-- Async
exports.oxmysql:transaction(_queries, _params, _callback, _logErrors)
exports.oxmysql:transaction(_queries, _callback, _logErrors)

-- Sync
exports.oxmysql:transactionSync(_queries, _params, _logErrors)
exports.oxmysql:transactionSync(_queries, _logErrors)
```

2021-09-19 16:12 UTC, dunak-debug commented
I would leave this error logging enabled by default. Soon I want to implement `mysql_log_level` that will define whether to print errors/warnigs.

2021-09-19 16:19 UTC, darksaid98 commented
> I would leave this error logging enabled by default without any param. Soon I want to implement `mysql_log_level` that will define whether to print errors/warnigs. This syntax is also new to people and as you know people are used to ghmatti syntax and we want to provide them 1:1 alternative. There is so many problems because of this compatibility like not defined callbacks throwing warning and people think that its error..

Yea the backward compatibility is quite painful. Reverted error logging stuff, anything else you can think of that needs doing here on my end?

2021-09-19 16:21 UTC, dunak-debug commented
I am gonna test it. Btw. what does transaction isolation level does? I never used transactions so thats new thing to me.

2021-09-19 17:11 UTC, darksaid98 commented
> I am gonna test it. Btw. what does transaction isolation level does? I never used transactions so thats new thing to me.

https://en.wikipedia.org/wiki/Isolation_(database_systems) TLDR the isolation level defines the rules by which different transactions may interact with the same data. It could be made configurable with an optional convar however I doubt many people would be interested in changing the isolation level.

2021-09-19 18:10 UTC, darksaid98 commented
Allows setting isolation level for transactions through convar `mysql_transaction_isolation_level`.  

The default value is `2`, it accepts integers 1-4.
```Js
  case 1:
    isolationLevel = 'SET TRANSACTION ISOLATION LEVEL REPEATABLE READ';
    break;
  case 2:
    isolationLevel = 'SET TRANSACTION ISOLATION LEVEL READ COMMITTED';
    break;
  case 3:
    isolationLevel = 'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED';
    break;
  case 4:
    isolationLevel = 'SET TRANSACTION ISOLATION LEVEL SERIALIZABLE';
    break;
```

2021-09-20 11:11 UTC, dunak-debug requested changes
Great work! Just a bit of changes and it´s ready to release 👍 

(I could be wrong, dont take it 100% seriously if it can´t be done this way or it´s better done by other way)

2021-09-20 11:11 UTC, dunak-debug commented on wrapper.lua
> +-- @param queries string
Should be table.

2021-09-20 11:11 UTC, dunak-debug commented on src/transaction.js
> +    return false;
No need to return because we are returning false to callback inside `safeCallback.. || false`.

2021-09-20 11:11 UTC, dunak-debug commented on src/transaction.js
> +const resourceName = GetCurrentResourceName() || 'oxmysql';
Could you transfer that to `config.js` and re-use it in both execute and transaction?

2021-09-20 11:13 UTC, dunak-debug commented on src/transaction.js
> +    await connection.release();
Also doesn´t need to return false. In `safeCallback()` we are returning `result || false`.

2021-09-20 13:29 UTC, darksaid98 commented on src/parser.js
> +    if (typeof query === 'string' || typeof query === 'number') {
Yup, it was.

2021-09-20 14:16 UTC, darksaid98 reviewed
Done.

2021-09-20 14:44 UTC, dunak-debug approved these changes
Great! I will edit some things so I won´t bother you more and release. 

**Thanks for your contribution!**

2021-09-20 14:48 UTC, merged